name             "apptentive_zookeeper"
maintainer       "Apptentive, Inc."
maintainer_email "blake@apptentive.com"
license          "mit"
description      "Installs zookeeper"
long_description "Installs zookeeper"
version          "0.1.1"
